# Generated by Django 5.1.1 on 2024-10-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("Consulta Médica", "Consulta Médica"),
                            ("Exame Laboratorial", "Exame Laboratorial"),
                            ("Vacinação", "Vacinação"),
                        ],
                        max_length=50,
                    ),
                ),
                ("professional", models.CharField(max_length=100)),
                ("datetime", models.DateTimeField()),
            ],
        ),
    ]
