# Generated by Django 5.1.1 on 2024-10-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instituicao", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="is_booked",
            field=models.BooleanField(default=False),
        ),
    ]
