# Generated by Django 5.1.1 on 2024-10-24 00:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("instituicao", "0003_appointment_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="user",
        ),
    ]
